import type { SubAgentRegistration } from "@jue/shared-types";

export const SUBAGENT_INVOKE_TOOL_NAME = "subagent.invoke";

export const READ_ONLY_SUBAGENT_TOOLS = [
  "file.read",
  "fs.tree",
  "fs.find",
  "search.text",
  "todo.list",
  "todo.read",
] as const;

export const PLANNING_SUBAGENT_TOOLS = [
  "file.read",
  "fs.tree",
  "fs.find",
  "search.text",
  "ask_user_question",
  "todo.list",
  "todo.read",
] as const;

export const GENERAL_SUBAGENT_TOOLS = [
  "file.read",
  "file.write",
  "file.edit",
  "fs.tree",
  "fs.find",
  "search.text",
  "shell.run",
  "monitor.start",
  "task.output",
  "task.stop",
  "http.request",
  "skill.invoke",
  "ask_user_question",
  "todo.create",
  "todo.update",
  "todo.list",
  "todo.read",
] as const;

const SENSITIVE_KEYS = ["apiKey", "token", "password", "secret", "authorization", "cookie"];

export function createDefaultSubAgentRegistrations(): SubAgentRegistration[] {
  return [
    {
      type: "explorer",
      invocationName: "ExplorerAgent",
      displayName: "ExplorerAgent",
      description: "快速只读代码探索子智能体，用于定位文件、定义、引用和关键字匹配。它不是代码评审员或架构分析员，调用时必须指定搜索广度 quick / medium / very_thorough。",
      visibility: "public",
      executionMode: "agent_loop",
      promptNamespace: "subagents/explorer",
      defaultPolicy: {
        allowedContextTypes: ["environment", "task_state", "user_attachment", "conversation_short_term", "tool_summary"],
        allowedToolNames: [...READ_ONLY_SUBAGENT_TOOLS],
        deniedToolNames: [SUBAGENT_INVOKE_TOOL_NAME, "file.write", "file.edit", "shell.run", "monitor.start", "task.stop"],
        allowedMemoryScopes: ["project"],
        redactSensitiveKeys: SENSITIVE_KEYS,
        inheritFrontendCapabilities: false,
        allowSubAgentTools: false,
      },
      defaultBudget: { maxTokens: 8_000, maxToolCalls: 12, maxDurationMs: 120_000, maxRecursionDepth: 0 },
      outputFormat: defaultOutputFormat("explorer"),
      maxFailureCount: 3,
      enabled: true,
      metadata: { public: true, recommendedBreadth: ["quick", "medium", "very_thorough"] },
    },
    {
      type: "plan",
      invocationName: "PlanAgent",
      displayName: "PlanAgent",
      description: "软件架构与实施规划子智能体，负责输出实施步骤、关键文件、架构取舍、风险和验证方案。它不能编辑文件，也不能执行高风险命令。",
      visibility: "public",
      executionMode: "agent_loop",
      promptNamespace: "subagents/plan",
      defaultPolicy: {
        allowedContextTypes: ["environment", "task_state", "user_attachment", "conversation_short_term", "tool_summary", "subagent_summary"],
        allowedToolNames: [...PLANNING_SUBAGENT_TOOLS],
        deniedToolNames: [SUBAGENT_INVOKE_TOOL_NAME, "file.write", "file.edit", "shell.run", "monitor.start", "task.stop", "plan.exit"],
        allowedMemoryScopes: ["project", "global"],
        redactSensitiveKeys: SENSITIVE_KEYS,
        inheritFrontendCapabilities: false,
        allowSubAgentTools: false,
      },
      defaultBudget: { maxTokens: 10_000, maxToolCalls: 10, maxDurationMs: 180_000, maxRecursionDepth: 0 },
      outputFormat: defaultOutputFormat("plan"),
      maxFailureCount: 3,
      enabled: true,
      metadata: { public: true },
    },
    {
      type: "verification",
      invocationName: "verification",
      displayName: "verification",
      description: "只读代码质量检查子智能体，审查实现质量、行为回归、测试缺口和架构风险。它返回 findings 和修复计划，但绝不修改文件。",
      visibility: "public",
      executionMode: "agent_loop",
      promptNamespace: "subagents/verification",
      defaultPolicy: {
        allowedContextTypes: ["environment", "task_state", "user_attachment", "conversation_short_term", "tool_summary", "tool_result_history", "subagent_summary"],
        allowedToolNames: [...READ_ONLY_SUBAGENT_TOOLS],
        deniedToolNames: [SUBAGENT_INVOKE_TOOL_NAME, "file.write", "file.edit", "shell.run", "monitor.start", "task.stop"],
        allowedMemoryScopes: ["project"],
        redactSensitiveKeys: SENSITIVE_KEYS,
        inheritFrontendCapabilities: false,
        allowSubAgentTools: false,
      },
      defaultBudget: { maxTokens: 10_000, maxToolCalls: 12, maxDurationMs: 180_000, maxRecursionDepth: 0 },
      outputFormat: defaultOutputFormat("verification"),
      maxFailureCount: 3,
      enabled: true,
      metadata: { public: true },
    },
    {
      type: "general",
      invocationName: "General-purpose",
      displayName: "General-purpose",
      description: "受边界约束的通用执行子智能体，用于完成独立任务。父 Agent 必须提供任务类型、具体目标、成功标准、约束和最小必要背景。",
      visibility: "public",
      executionMode: "agent_loop",
      promptNamespace: "subagents/general",
      defaultPolicy: {
        allowedContextTypes: ["environment", "task_state", "user_attachment", "conversation_short_term", "tool_summary", "tool_result_history", "subagent_summary"],
        allowedToolNames: [...GENERAL_SUBAGENT_TOOLS],
        deniedToolNames: [SUBAGENT_INVOKE_TOOL_NAME],
        allowedMemoryScopes: ["project", "global", "user"],
        redactSensitiveKeys: SENSITIVE_KEYS,
        inheritFrontendCapabilities: false,
        allowSubAgentTools: false,
      },
      defaultBudget: { maxTokens: 12_000, maxToolCalls: 16, maxDurationMs: 240_000, maxRecursionDepth: 0 },
      outputFormat: defaultOutputFormat("general"),
      maxFailureCount: 3,
      enabled: true,
      metadata: { public: true },
    },
    {
      type: "memory_extractor",
      invocationName: "MemoryExtractorAgent",
      displayName: "MemoryExtractorAgent",
      description: "内部记忆提取子智能体，保守识别明确的长期记忆候选，并通过 memory 管线提交结构化候选。",
      visibility: "internal",
      executionMode: "rule",
      promptNamespace: "subagents/memory_extractor",
      defaultPolicy: {
        allowedContextTypes: ["user_input", "recent_messages", "task_state"],
        allowedToolNames: [],
        deniedToolNames: [SUBAGENT_INVOKE_TOOL_NAME, "file.write", "file.edit", "shell.run", "monitor.start"],
        allowedMemoryScopes: [],
        redactSensitiveKeys: SENSITIVE_KEYS,
        inheritFrontendCapabilities: false,
        allowSubAgentTools: false,
      },
      defaultBudget: { maxTokens: 3_000, maxToolCalls: 0, maxDurationMs: 30_000, maxRecursionDepth: 0 },
      outputFormat: defaultOutputFormat("memory_extractor"),
      maxFailureCount: 3,
      enabled: true,
      metadata: { internalTrigger: "turn.finished", ruleRunner: true },
    },    {
      type: "dream_memory_pruning",
      invocationName: "DreamMemoryPruning",
      displayName: "DreamMemoryPruning",
      description: "内部后台记忆整理子智能体，在 agent 关闭或维护窗口整理过期、重复、冲突和过长记忆。",
      visibility: "internal",
      executionMode: "rule",
      promptNamespace: "subagents/dream_memory_pruning",
      maxFailureCount: 3,
      enabled: true,
      metadata: { internalTrigger: "agent.close", ruleRunner: true },
    },
    {
      type: "dream_observation_pruning",
      invocationName: "DreamObservationPruning",
      displayName: "DreamObservationPruning",
      description: "Internal background observation pruning agent. It consolidates style-observation-pool.json into durable memory and removes stale or low-confidence candidates.",
      visibility: "internal",
      executionMode: "rule",
      promptNamespace: "subagents/dream_observation_pruning",
      maxFailureCount: 3,
      enabled: true,
      metadata: { internalTrigger: "agent.close", ruleRunner: true, phase: "observation_pool" },
    },
    {
      type: "session_search",
      invocationName: "SessionSearch",
      displayName: "SessionSearch",
      description: "内部会话记忆搜索子智能体，由 session 层在新会话启动时触发，搜索相关 summary.md 并注入必要背景。",
      visibility: "internal",
      executionMode: "rule",
      promptNamespace: "subagents/session_search",
      defaultPolicy: {
        allowedContextTypes: ["environment", "user_input", "task_state", "subagent_summary"],
        allowedToolNames: ["search.text", "file.read"],
        deniedToolNames: [SUBAGENT_INVOKE_TOOL_NAME, "file.write", "file.edit", "shell.run", "monitor.start"],
        allowedMemoryScopes: [],
        redactSensitiveKeys: SENSITIVE_KEYS,
        inheritFrontendCapabilities: false,
        allowSubAgentTools: false,
      },
      defaultBudget: { maxTokens: 4_000, maxToolCalls: 4, maxDurationMs: 60_000, maxRecursionDepth: 0 },
      outputFormat: defaultOutputFormat("session_search"),
      maxFailureCount: 3,
      enabled: true,
      metadata: { internalTrigger: "session.new" },
    },
  ];
}

function defaultOutputFormat(agent: string): string {
  return [
    "只返回一个 JSON 对象，不要使用 Markdown 代码块，不要输出额外说明或内部推理过程。",
    "必填字段：conclusion, details, evidence, risks, suggestedActions, outputs。",
    "conclusion：一句话中文结论。",
    "details：必要的中文细节说明；如果没有额外细节，使用空字符串。",
    "evidence：数组，元素格式为 { id, kind, ref?, summary }，summary 必须说明证据来源和意义。",
    "risks：数组，元素格式为 { level, description, mitigation? }，level 使用 low/medium/high。",
    "suggestedActions：数组，元素格式为 { id, label, description?, toolName?, arguments? }。",
    "outputs 必须包含 agent，并根据子智能体类型包含 files、symbols、planSteps、findings、completedWork、matchedSessions 或 notes 等结构化结果。",
    `outputs.agent 必须设置为 ${JSON.stringify(agent)}。`,
  ].join("\n");
}


